language: java
jdk:
  - oraclejdk11
branches:
  only:
    - master
before_install:
  - chmod +x ./gradlew
script:
  - ./gradlew check
  - ./gradlew codeCoverageReport
after_script:
  - bash <(curl -s https://codecov.io/bash -t "$CODECOV_TOKEN")
