language: java
jdk:
  - oraclejdk11
env:
  - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dglass.platform=Monocle -Dmonocle.platform=Headless -Dtestfx.setup.timeout=25000"
branches:
  only:
    - master
before_install:
  - chmod +x ./gradlew
script:
  - ./gradlew check
  - ./gradlew codeCoverageReport
after_script:
  - bash <(curl -s https://codecov.io/bash -t "$CODECOV_TOKEN")
