package de.uniks.stp.jpa;

public enum AccordSettingKey {
    LANGUAGE, LAST_USER_LOGIN, NOTIFICATION_SOUND, AUDIO_IN_DEVICE, AUDIO_OUT_DEVICE, AUDIO_OUT_VOLUME, AUDIO_IN_SENSITIVITY, AUDIO_IN_VOLUME
}
